### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by gnewton** [mjibson/moggio#49]
Loading 2900 songs from local disk (not a lot), and running ~10 minutes, memory usage was 425MB resident and 1.5GB virtual. Realistically, this should be able to run in <100MB resident, <200MB virtual.

Linux, downloaded 64bit version.

**Comment by mjibson** [comment]
In order to support seeking backward in time, moggio currently keeps the decoded song in memory, and this indeed takes up a ridiculous amount of memory. Changing this so that it instead keeps the encoded song in memory and re-decodes on the fly if a user seeks is what I'd like to do. That will increase the time it takes to seek (since it has to re-decode the file) but the memory savings are worth it since seeking isn't that common.

**Comment by mjibson** [comment]
Dup of #36
